# Generated by Django 4.1.2 on 2022-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='automoviles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_de_fabricacion', models.CharField(max_length=100)),
                ('kilometraje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='camionetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_de_fabricacion', models.CharField(max_length=100)),
                ('kilometraje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_de_fabricacion', models.CharField(max_length=100)),
                ('kilometraje', models.CharField(max_length=50)),
            ],
        ),
    ]
